print("sudo apt-get update")
print("sudo apt install vsftpd")
print("sudo cp /etc/vsftpd.conf /etc/vsftpd.conf.orig")
print("sudo ufw status")
print("sudo ufw allow 20/tcp")
print("sudo ufw allow 21/tcp")
print("sudo ufw allow 990/tcp")
print("sudo ufw allow 40000:50000/tcp")
print("sudo ufw status")
print("sudo adduser sadio")
print("sudo mkdir /home/sadio/ftp")
print("sudo chown nobody:nogroup /home/sadio/ftp")
print("sudo chmod a-w /home/sadio/ftp")
print("sudo mkdir /home/sadio/ftp/files")
print("sudo chown sadio:sadio /home/sadio/ftp/files")